[project]
name = "plex2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "plexapi>=4.17.0",
    "requests>=2.32.4",
    "thefuzz>=0.22.1",
]
